name: Build multi-bundle APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build release APK (debug-signed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          _JAVA_OPTIONS: "-Djava.awt.headless=true"
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleRelease -PsignAsDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: app/build/outputs/apk/release/*.apk
